### ISSUE TITLE
OOM error - java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by vikas027** [SonarSource/sonarqube-scan-action#17]
## Environment
- Sonarqube Developer EditionVersion 9.0.1 (build 46107)
- GitHub Actions [Custom Runners](https://github.com/actions-runner-controller/actions-runner-controller) on Kubernetes Cluster

## Problem
Sonarqube scans fail with the below error even though the GitHub Actions controller pod has enough memory, around `4Gi`
```bash
Exception in thread "global symbols computation progress" java.lang.OutOfMemoryError: Java heap space
107
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
108
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
109
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
110
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:174)
111
	at org.sonarsource.analyzer.commons.ProgressReport.run(ProgressReport.java:62)
112
	at java.base/java.lang.Thread.run(Thread.java:829)
113
INFO: ------------------------------------------------------------------------
114
INFO: EXECUTION FAILURE
115
INFO: ------------------------------------------------------------------------
116
INFO: Total time: 2:21.626s
117
ERROR: Error during SonarScanner execution
118
INFO: Final Memory: 19M/121M
119
java.lang.OutOfMemoryError: Java heap space
120
INFO: ------------------------------------------------------------------------
121
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
122
	at java.base/java.util.ArrayList.toArray(ArrayList.java:401)
123
	at java.base/java.util.ArrayList.<init>(ArrayList.java:179)
124
	at org.sonar.sslr.internal.matchers.ParseNode.<init>(ParseNode.java:39)
125
	at org.sonar.sslr.internal.vm.Machine.createNode(Machine.java:256)
126
	at org.sonar.sslr.internal.vm.Instruction$RetInstruction.execute(Instruction.java:305)
127
	at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:162)
128
	at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:105)
129
	at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:61)
130
	at com.sonar.sslr.impl.Parser.parse(Parser.java:84)
131
	at org.sonar.python.parser.PythonParser$SslrPythonParser.parse(PythonParser.java:83)
132
	at org.sonar.python.parser.PythonParser.parse(PythonParser.java:49)
133
	at org.sonar.python.types.TypeShed.builtinSymbols(TypeShed.java:92)
134
	at org.sonar.python.semantic.SymbolTableBuilder$FirstPhaseVisitor.visitFileInput(SymbolTableBuilder.java:277)
135
	at org.sonar.python.tree.FileInputImpl.accept(FileInputImpl.java:79)
136
	at org.sonar.python.semantic.SymbolTableBuilder.visitFileInput(SymbolTableBuilder.java:130)
137
	at org.sonar.python.types.TypeShed.getModuleSymbols(TypeShed.java:247)
138
	at org.sonar.python.types.TypeShed.searchTypeShedForModule(TypeShed.java:203)
139
	at org.sonar.python.types.TypeShed.symbolsForModule(TypeShed.java:163)
140
	at org.sonar.python.types.TypeShed.symbolWithFQN(TypeShed.java:172)
141
	at org.sonar.python.semantic.Scope.addImportedSymbol(Scope.java:201)
142
	at org.sonar.python.semantic.SymbolTableBuilder$FirstPhaseVisitor.lambda$createImportedNames$0(SymbolTableBuilder.java:395)
143
	at org.sonar.python.semantic.SymbolTableBuilder$FirstPhaseVisitor$$Lambda$1129/0x0000000100aa4440.accept(Unknown Source)
144
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
145
	at org.sonar.python.semantic.SymbolTableBuilder$FirstPhaseVisitor.createImportedNames(SymbolTableBuilder.java:383)
146
	at org.sonar.python.semantic.SymbolTableBuilder$FirstPhaseVisitor.visitImportFrom(SymbolTableBuilder.java:377)
147
	at org.sonar.python.tree.ImportFromImpl.accept(ImportFromImpl.java:120)
148
	at org.sonar.plugins.python.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:33)
149
	at org.sonar.plugins.python.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:40)
150
	at org.sonar.plugins.python.api.tree.BaseTreeVisitor.visitStatementList(BaseTreeVisitor.java:52)
151
	at org.sonar.python.tree.StatementListImpl.accept(StatementListImpl.java:46)
152
	at org.sonar.plugins.python.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:33)
```

I have monitored the pod resources while the scan was running and it never showed any signs of resource crunch.
```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7608        1710        1827           2        4070        5697
Swap:             0           0           0
$ 
``` 

Everything else on the GitHub Actions is running fine, I am running out of ideas. Anything else I can do to troubleshoot the issue?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @vikas027 ,

this would require a bit more information. can you create a thread in our [community forum](https://community.sonarsource.com/) about this issue?
apart from that you can try to increase the java heap space [as described in our docs](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/#header-9). maybe this will already resolve your issue
