### ISSUE TITLE
Fail to create working dir: /github/workspace/.scannerwork

### ISSUE THREAD

**Issue by brian-pickens** [SonarSource/sonarqube-scan-action#67]
I seem unable to scan my Go project. I'm executing my action in a self-hosted runner. Is there a permission or something I need to fix in my self-hosted runner to resolve this? It appears though that the permission issue exists in the sonar-scanner-cli-docker container.
```
Caused by: java.lang.IllegalStateException: Fail to create working dir: /github/workspace/.scannerwork
	at org.sonar.scanner.scan.WorkDirectoriesInitializer.mkdirWorkingDir(WorkDirectoriesInitializer.java:79)
	at org.sonar.scanner.scan.WorkDirectoriesInitializer.execute(WorkDirectoriesInitializer.java:52)
	at org.sonar.scanner.scan.InputProjectProvider.provide(InputProjectProvider.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:[154](https://github.com/SunriseBanks/ach-csv-converter/actions/runs/4767113541/jobs/8475320941#step:6:155))
	... 60 more
Caused by: java.nio.file.AccessDeniedException: /github/workspace/.scannerwork
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
	at org.sonar.scanner.scan.WorkDirectoriesInitializer.mkdirWorkingDir(WorkDirectoriesInitializer.java:77)
	... 67 more
```

In addition, the "Post" cleanup up step appears to be failing, reporting errors such as:

```
chown: ./models: Operation not permitted
```

**Comment by csaba-feher-sonarsource** [comment]
Possibly moving the same changes over from sonarcloud-scan-action will solve the issues. 
https://github.com/SonarSource/sonarqube-scan-action/issues/94

**Comment by istvan-bodo-sonarsource** [comment]
Thank you for your feedback. A ticket has been created to update the cleanup process:
https://sonarsource.atlassian.net/browse/SQSCANGHA-29

Also, there is a known problem with GitHub actions when self-hosted runners are used, you can find the related issue here:
https://github.com/actions/runner/issues/434
