### ISSUE TITLE
ERROR: SonarQube server [***] can not be reached from self hosted runner even though URL is whitelisted

### ISSUE THREAD

**Issue by Keshapally** [SonarSource/sonarqube-scan-action#91]
Hi Team,

I'm facing below error.

ERROR: SonarQube server [***] can not be reached from self hosted runner even though URL is whitelisted in it.
Also, my SRE Team says that Servers in our INTERNAL Active Directory domains already has Root and Intermediate certificates installed.

Java projects are scanned via same self hosted runner successfully with some command like "mvn clean verify sonar:sonar" whereas i get error for python projects when i use this action.

```
action used
- name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.0.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
```

```
ERROR: SonarQube server [***] can not be reached
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 0.467s
ERROR: Error during SonarScanner execution
INFO: Final Memory: 19M/224M
INFO: ------------------------------------------------------------------------
org.sonarsource.scanner.api.internal.ScannerException: Unable to execute SonarScanner analysis
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:85)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:3[18](https://github.com/procter-gamble/OTR-ModernServices/actions/runs/7192769763/job/19589863792#step:4:19))
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:74)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:70)
	at org.sonarsource.scanner.api.EmbeddedScanner.doStart(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.start(EmbeddedScanner.java:1[23](https://github.com/procter-gamble/OTR-ModernServices/actions/runs/7192769763/job/19589863792#step:4:24))
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: java.lang.IllegalStateException: Fail to get bootstrap index from server
	at org.sonarsource.scanner.api.internal.BootstrapIndexDownloader.getIndex(BootstrapIndexDownloader.java:42)
	at org.sonarsource.scanner.api.internal.JarDownloader.getScannerEngineFiles(JarDownloader.java:58)
	at org.sonarsource.scanner.api.internal.JarDownloader.download(JarDownloader.java:53)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:76)
	... 7 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by henryju** [comment]
Have you tried passing the SSL certificate to the scanner using SONAR_ROOT_CERT? The README provides more details.

We are closing the GitHub issues section, if you need more help, please open a thread on our [community forum](https://community.sonarsource.com/).
